@Restaurants.API_HostAddress = https://localhost:7005
@token = CfDJ8KVbLN8YEC5BlUb1WUVOv2VIEqQAgAmkcKffw7YKaQsZm6toUx2e49sB_4jWU0j19UXlaaiMDNaRcfNGhOzQvtGHHsYQKGtwEG1vqxdL-QHF4Rt2VecKp3r_Qe-nVvHlybXBAtni010KbOjbbk5g_zINXt3VKGnbpEN9mhW7m23o4JpCtjvWckePUAm2O3orzcoOKjbtvHqIHgbPV9ekNxSrgFGqKESCH_phUD1jq7jdDurX5bJ0W8cgvAbysNYLTNLCaVquKJFeyZyDz21js5pK24lZKKKIHpCDUD8_JBWhKR48W8L7tV_R5S1YX837yaWYqqnyVGNlWg5-syKbf1xhipKf5BXl9fFJ1iw71-RSjln3FaH8uRl6ezakWIvwq1or1nNE_I3BaaQAMI00kjD-gS0YaF8T9Vrd5vYTPXSx4TWbYfyYl-wTqWRve61gHKJFlIGPGSPVr0TJUA0tkxqoWid2sBQXVPuVVoZrd2MkJmJR9Up1AwZzkD9srneVXiaIysMKuCzinvaj0ND_7VTmk2zDmitO8pTXJW1lST26YKQzPgt7ioc1Ika7hiCbpxyQ5Qrj5_Z1TS9TC7jEEdBkj3hgspcqng1ShDqaEMJ7a8s4SnAmlMtUJU8vNlkTSzhhINqQPmcRQrXL0Kem4zk94SlNcK5cbicrLH1JM814ebbxeCeDGitJzCFeHrNQYs_JRsu6Xkp-hQPfGrnOtTOWo8uF7GQ3FF_9VD0DydDLnnWKClsopQF4UX6cK6os2EfuAUSg2t8_1bLmbcClraI

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###

@id=1012
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Sample Restaurant",
  "description": "A sample description of the restaurant.",
  "category": "Italian",
  "hasDelivery": true,
  "contactEmail": "sample@example.com",
  "contactNumber": "+1234567890",
  "city": "Sample City",
  "street": "123 Sample Street",
  "postalCode": "12-345"
}

###

GET https://localhost:7005/api/restaurants/1007

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/9

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1011
Content-Type: application/json

{
  "name": "Ngoc Han",
  "description": "A sample description of the restaurant.",
    "hasDelivery": true
}
###

POST {{Restaurants.API_HostAddress}}/api/restaurant/1012/dishes
Content-Type: application/json

{
  "Name": "Ga chien",
  "Description": "Ngonn",
  "Price": 100,
  "KiloCalories": 100
}

###

@restaurantId=1012
GET {{Restaurants.API_HostAddress}}/api/restaurant/{{restaurantId}}/dishes

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1009

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nationality": "VietNam",
  "dateofbirth": "2025-01-19"
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner@gmail.com",
  "password": "Owner123!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "User123!"
}