@Restaurants.API_HostAddress = https://localhost:7005
@token = CfDJ8KVbLN8YEC5BlUb1WUVOv2WSkdnjcrcaIGG7Su4aoawmaGpaHS6cf8draXXYNLW3Ufw8Yy79vz2VOYV1AOln_RNxI0ndfggqzI-BfAIwTsF7dEW4fCPt--E8P4FdPf2lTyX2UNNg76QIpjgYDN04OCQy0klfxu8yZ2Km3W_ArVyhRHlFhB55nTR8pGqFCc9Xx9AlanAbMy94IKKeszj_2nysiJXurajU6UBbPRx9s4coW4QuwgpYoTyBt_EwYssDG9spOIyb7ws614opUaIUzejgHs4ro_INbfyXei3hsnvbwbXa4EoFivvbD7AquR79TvjXQdolmYu2ZnHxgLzgQrw63_YlpycJRRCXxuo8OxRuVtxDVb9lyFzxR4RAu0PJ4LWM2lbWexMKYx1KhyKTzWIYYkEloSa3uBcQJMooSnyGPI8sqj-IIuKhMnckS7uQjGB_OUt8HZ_NdOsORh6OAvIr8lvieKe9Fuj0RaBbg0l56P95l-9QvFagI_UcHHsrYJyQWF-mHR_LQmCV1KYLkihRwHRQD7XNZsyfZ_ADt0j4SVUJ5fld-j25ZzjtVC1Z9Me9fu97ys0W7B0cqnpsSEw0XV9qvGCJbqRphkObcl5pRBD3doxn9gPoP0-U7hzI-_HB17BhTWqZzqVJzrrv1H8e-gFqboOuIE100B7k8-tOeEZynFBP25MvMf1FxpY9PQ

GET {{Restaurants.API_HostAddress}}/api/restaurants
#Authorization: Bearer {{token}}

###

@id=1012
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Sample Restaurant",
  "description": "A sample description of the restaurant.",
  "category": "Italian",
  "hasDelivery": true,
  "contactEmail": "sample@example.com",
  "contactNumber": "+1234567890",
  "city": "Sample City",
  "street": "123 Sample Street",
  "postalCode": "12-345"
}

###

GET https://localhost:7005/api/restaurants/1007

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/9

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1011
Content-Type: application/json

{
  "name": "Ngoc Han",
  "description": "A sample description of the restaurant.",
    "hasDelivery": true
}
###

POST {{Restaurants.API_HostAddress}}/api/restaurant/1012/dishes
Content-Type: application/json

{
  "Name": "Ga chien",
  "Description": "Ngonn",
  "Price": 100,
  "KiloCalories": 100
}

###

@restaurantId=1012
GET {{Restaurants.API_HostAddress}}/api/restaurant/{{restaurantId}}/dishes

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1009

###
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner@gmail.com",
  "password": "Owner123!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@gmail.com",
  "password": "Owner123!"
}