@Restaurants.API_HostAddress = https://localhost:7005
@token = CfDJ8KVbLN8YEC5BlUb1WUVOv2WuhQqfpiaVSqimKHwuzrLtYG0qTdS8ALhhMiVOwADD9SwsJHpLRI1NlZeEIaqH__7lfmiqHsLxdz9Vr5amQ9Rg4dI3gu797LtCAN7SXPi7z6auPzF5dxNoMuk4y00SiBxOS6itZDqgJIq1dkInNYaovZu3lj0S_ac_DHDoen6ztWDpJwvcK825WiHMynV-Z2F9iNC4DGmtHK807TibpzLNfYqgt92GY_rAcpZPbQwX6tbbHKYAMTFIpdAi_UiuO0Gt6FzQvdV6ferM3e2vonI8pP1AKTnKfYb404m-cFZXxDHFDByJapWkVIO8F41DXUejNjwL8UHcBsYIwrS1tUCsWFL6WdZDdvHbQz8OI14VRd1gHURQDukFV1X_DmsjVnzUN4zs6WCdX1iCw5BJyOjIvl0IIZbTP866jWmiExUoJ-aZkJZgxn93SH_nhsqRoxFgKPJ7TnCjm-fIb6Rq7Z469KtZqupoO0PvGA_NDVqBH4SliQxqN8Cb4Sk7NRnMNr-HcU_sMEUpsc_JrSeFWPc7_kDz566742xIeBT83j56gYmDJ_U1NbT_NSom7TnM21PegYuxvh2Dq0StpEJ_V_wXcFPBHbAhuEeOgKkucVO4ZruEZQ7tKaHGg-Mj7kwZrMQz9-c9aRVzQTb_EBczWo8AW0QzsAZP1iLYz-xi8LzTWv9-5A2XyMwMkvff7N2bay6fYkIZx_KNc8dGZ7tlbtiHlnpSFPdDBdRyCdThriANkNmbPvwZKIXNbDSfl3u2KbGdjEkoqeVrGcKEKguV0-wEhXG_y-CeB-zSPQIoJlilg-3JJMafH-OLk1hysJJM8VlV4SNBvCL0pXy1oCeNpkxQH7wRgq3dATwwnsij6FbjZw

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###

@id=1012
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "KFC-Nghia",
  "description": "Rat ngon",
  "category": "Italian",
  "hasDelivery": true,
  "contactEmail": "kfc-nghia@gmail.com",
  "contactNumber": "1234567890",
  "city": "ThuDuc",
  "street": "ManThien",
  "postalCode": "12-123"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nationality": "VietNam",
  "dateofbirth": "2003-05-17"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@gmail.com",
  "password": "Owner123!"
}

###

